parameters:
    nibynool_fitbit.key: ''
    nibynool_fitbit.secret: ''
    nibynool_fitbit.callback: ''
    nibynool_fitbit.configuration: []
services:
    fitbit:
        class:     Nibynool\FitbitInterfaceBundle\Fitbit\ApiGatewayFactory
        arguments: [%nibynool_fitbit.key%, %nibynool_fitbit.secret%, %nibynool_fitbit.callback%, %nibynool_fitbit.configuration%, @router]